auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

memberlist:
  join_members:
    - loki:7946

schema_config:
  configs:
    - from: 2021-08-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      bucketnames: loki-data
      access_key_id: loki
      secret_access_key: supersecret
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist
  compactor_address: http://compactor:3100
  compactor_grpc_address: compactor:9095

# Compactor 설정
compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  delete_request_store: s3

# Query Scheduler 설정
query_scheduler:
  max_outstanding_requests_per_tenant: 2048

# Querier 설정 (engine 제거)
querier:
  max_concurrent: 4

# Query Range 설정
query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 1024
        ttl: 24h

# Frontend 설정
frontend:
  scheduler_address: query-scheduler:9095
  log_queries_longer_than: 5s
  compress_responses: true
  max_outstanding_per_tenant: 2048

# Limits 설정 (여기에 쿼리 타임아웃 설정)
limits_config:
  retention_period: 744h
  split_queries_by_interval: 24h
  max_query_parallelism: 32
  query_timeout: 5m

# Ruler 설정
ruler:
  storage:
    s3:
      bucketnames: loki-ruler
  rule_path: /loki/rules-temp
  ring:
    kvstore:
      store: memberlist

# Chunk Store Cache 설정
chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 1024
      ttl: 24h